name: Deployment

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - uses: actions/checkout@v3
      - name: Calculate version
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Google Cloud Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: gcloud configuration
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: gcloud and Docker integration
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Download image
        run: docker pull europe-west2-docker.pkg.dev/earelin/admin-levels-gz/admin-levels-gz:${{ steps.commit.outputs.short }}
      - name: Tag image
        run: docker tag europe-west2-docker.pkg.dev/earelin/admin-levels-gz/admin-levels-gz:${{ steps.commit.outputs.short }} europe-west2-docker.pkg.dev/earelin/admin-levels-gz/admin-levels-gz:${{ steps.tag.outputs.tag }}
      - name: Push versioned image to repository
        run: docker push europe-west2-docker.pkg.dev/earelin/admin-levels-gz/admin-levels-gz:${{ steps.tag.outputs.tag }}

      - name: Update containers
        run: gcloud run deploy admin-levels-gz --region europe-west2 --image europe-west2-docker.pkg.dev/earelin/admin-levels-gz/admin-levels-gz:${{ steps.tag.outputs.tag }}
